[workspace]
resolver = "2"
members = ["auth","database",
	"protocol",
    "server",
]
exclude = [
]

[workspace.package]
version = "0.0.1"
edition = "2024"

[workspace.dependencies]
time = { version = "0.3.55", features = ["serde"] }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uuid = { version = "1.26.1", features = ["v7", "serde"] }
base64 = "0.23"

[workspace.lints.rust]
async_fn_in_trait = "allow"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

indexing_slicing = "warn"
undocumented_unsafe_blocks = "warn"

large_enum_variant = "allow"
match_wildcard_for_single_variants = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
result_large_err = "allow"
zero_sized_map_values = "allow"
too_many_lines = "allow"

# Give me the best optimizations you've got, Rust
[profile.release]
codegen-units = 1
# lto = true
opt-level = 3
