[package]
name = "auth"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
serde.workspace = true
uuid.workspace = true
base64.workspace = true
argon2 = "0.6"
jsonwebtoken = "11.1"
rand = { version = "0.10.3", features = ["chacha"] }

[lints]
workspace = true
