// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Block = { id: string, created_at: Date, modified_at: Date, markdown: string | null, link: string | null, image: string | null, };

export type BlockCreate = { id: string, markdown: string | null, link: string | null, image: string | null, };

export type BlockUpdate = { id: string, markdown: string | null, link: string | null, image: string | null, };
