// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Collection = { id: string, created_at: Date, modified_at: Date, owner_id: string, private: boolean, collaborators: Array<string>, name: string, important_blocks: Array<string>, blocks: Array<string>, };

export type CollectionCollaboratorUpdate = { important_blocks: Array<string>, blocks: Array<string>, };

export type CollectionCreate = { name: string, private: boolean, };

export type CollectionOwnerUpdate = { owner_id: string, private: boolean, collaborators: Array<string>, name: string, important_blocks: Array<string>, blocks: Array<string>, };
