// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, created_at: Date, username: string, nickname: string, email: string, avatar: string | null, bio: string, links: Array<string>, users_followed: Array<string>, collections_followed: Array<string>, landing_page: string, show_nsfw: boolean, };

export type UserCreate = { username: string, nickname: string, email: string, password: string, };

export type UserUpdate = { username: string | null, nickname: string | null, email: string | null, password: string | null, avatar: string | null, bio: string | null, links: Array<string> | null, users_followed: Array<string> | null, collections_followed: Array<string> | null, landing_page: string | null, show_nsfw: boolean | null, };
